# Generated by Django 5.2.4 on 2025-08-28 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_address', models.TextField()),
                ('payment_method', models.CharField(choices=[('BANK', 'Bank'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], max_length=50)),
                ('shipping_fee', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kleistic_app.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('THIS_MONTH', 'This Month'), ('OUR_PRODUCTS', 'Our Products'), ('FLASH_SALES', 'Flash Sales')], default='OUR_PRODUCTS', max_length=50)),
                ('main_category', models.CharField(choices=[("WOMEN'S FASHION", "Women's Fashion"), ("MEN'S FASHION", "Men's Fashion"), ('ELECTRONICS', 'Electronics'), ('GAMING', 'Gaming'), ("BABY'S AND TOYS", "Baby's and Toys"), ('GROCERIES AND PETS', 'Groceries and pets'), ('HEALTH AND BEAUTY', 'Health and beauty'), ('LIFESTYLE', 'Lifestyle'), ('SPORTS', 'Sports')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TimeStampField',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kleistic_app.product'),
        ),
    ]
