# Generated by Django 5.2.4 on 2025-08-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0002_order_orderitem_product_delete_timestampfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kleistic_app.product'),
        ),
    ]
