# Generated by Django 5.2.4 on 2025-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0003_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='ItemOrder',
        ),
    ]
