# Generated by Django 5.2.4 on 2025-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0004_rename_orderitem_itemorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='subtotal',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='grand_total',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
