# Generated by Django 5.2.4 on 2025-08-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0005_rename_subtotal_itemorder_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorder',
            old_name='total',
            new_name='item_total',
        ),
    ]
