# Generated by Django 5.2.4 on 2025-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0006_rename_total_itemorder_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[("WOMEN'S_FASHION", "Women's Fashion"), ("MEN'S_FASHION", "Men's Fashion"), ('ELECTRONICS', 'Electronics'), ('GAMING', 'Gaming'), ("BABY'S_AND_TOYS", "Baby's and Toys"), ('GROCERIES_AND_PETS', 'Groceries and pets'), ('HEALTH_AND_BEAUTY', 'Health and beauty'), ('LIFESTYLE', 'Lifestyle'), ('SPORTS', 'Sports')], max_length=200),
        ),
    ]
