# Generated by Django 5.2.4 on 2025-08-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0007_alter_product_main_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
