# Generated by Django 5.2.4 on 2025-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0010_rename_grand_total_order_total_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'Bank'), ('CASH ON DELIVERY', 'Cash on Delivery')], max_length=50),
        ),
    ]
