# Generated by Django 5.2.4 on 2025-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0011_remove_order_product_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
