# Generated by Django 5.2.4 on 2025-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleistic_app', '0014_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
